name: country_info_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

#  assets:
#    - fonts/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Axiforma
      fonts:
        - asset: fonts/Axiforma/Axiforma-Thin.ttf
          weight: 100
        - asset: fonts/Axiforma/Axiforma-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Axiforma/Axiforma-Light.ttf
          weight: 300
        - asset: fonts/Axiforma/Axiforma-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Axiforma/Axiforma-Regular.ttf
          weight: 400
        - asset: fonts/Axiforma/Axiforma-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Axiforma/Axiforma-Medium.ttf
          weight: 500
        - asset: fonts/Axiforma/Axiforma-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Axiforma/Axiforma-SemiBold.ttf
          weight: 600
        - asset: fonts/Axiforma/Axiforma-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Axiforma/Axiforma-Bold.ttf
          weight: 700
        - asset: fonts/Axiforma/Axiforma-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Axiforma/Axiforma-ExtraBold.ttf
          weight: 800
        - asset: fonts/Axiforma/Axiforma-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Axiforma/Axiforma-Black.ttf
          weight: 900
        - asset: fonts/Axiforma/Axiforma-BlackItalic.ttf
          weight: 900
          style: italic



